version: "3.8"
services: 
    sqldata:
        container_name: sql-data
        build:
            context: .
            dockerfile: sql/Dockerfile
        ports:
          - "1433:1433"
        volumes:
          - library-sqldata:/var/opt/mssql

    library:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT:Development
            - ConnectionStrings__DefaultConnection:Server=sqldata;Database=Library;User Id=sa;Password=Pass@word;Persist Security Info=True
        container_name: library
        ports: 
            - 5000:80
        depends_on: 
            - sqldata

volumes:
  library-sqldata:
    external: false